### ISSUE TITLE
Can't download ckpt files

### ISSUE THREAD

**Issue by kape67** [MkuuWaUjinga/leopart#3]
I tried to download ckpt files but I couldn't.

Could you check the links? 

Thanks.

**Comment by MkuuWaUjinga** [comment]
Hi there,

just checked the ckpt links and they worked for me (wget and using the Dropbox UI). Can you check again and provide the specific link in case it still does not work for you?

Thanks!

**Comment by kape67** [comment]
Thanks for reply.
 
Oh.. I have mistaken. ( I just noticed that it can't download in my lab )
 
The links worked in my home. Thank you!
 
 
 
 
-----Original Message-----
