### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by zhuzq-iziy** [MkuuWaUjinga/leopart#4]
Your work is great! Great inspiration for me!

But when I try to run the following code under fully unsupervised settings, we found that some files are missing (i.e., all_gt_masks_train_voc12.pt, all_gt_masks_val_voc12.pt, attn_voc_train.pt, attn_voc_val.pt) that prevent it from working properly. 

`python experiments/fully_unsup_seg/fully_unsup_seg.py --ckpt_path {vit-small-ckpt} --experiment_name vits16 --best_k 149 --best_mt 2 --best_et 0.09`

So could you share these files or give me methods for generating them?

Thank you very much!

**Comment by MkuuWaUjinga** [comment]
Hi there,

thanks for your interest and flagging this!

We updated the [readme](https://github.com/MkuuWaUjinga/leopart/blob/main/README.md#fully-unsupervised-semantic-segmentation) with links to the ViT-S/16 DINO attention masks we use as noisy ground truth for foreground. These are the last two files you mentioned. Note that we renamed them for clarity. The first two files should now be generated when the script is executed. So after pulling you should be good to go (hopefully). 

Cheers!

**Comment by zhuzq-iziy** [comment]
Thanks for reply.

It can work now. Thank you!
